apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-k8s-app
  template:
    metadata:
      labels:
        app: docker-k8s-app
    spec:
      containers:
      - name: docker-k8s-app
        image: docker-k8s-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-app-service
spec:
  type: NodePort
  selector:
    app: docker-k8s-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
